// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6FBWNCpJIaGh3w231l1faJDt9do6DyUU',
    appId: '1:442635216043:web:8d6241ee49b94e06dc83ee',
    messagingSenderId: '442635216043',
    projectId: 'pulse-45c54',
    authDomain: 'pulse-45c54.firebaseapp.com',
    storageBucket: 'pulse-45c54.firebasestorage.app',
    measurementId: 'G-44HRBJVKCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4uUxGpYyCITI_qjljlpRtMF5VGJJvBMQ',
    appId: '1:442635216043:android:75f8193dcdcec368dc83ee',
    messagingSenderId: '442635216043',
    projectId: 'pulse-45c54',
    storageBucket: 'pulse-45c54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsA-grYbenOCLuxz0uplBeSivelNKr_1M',
    appId: '1:442635216043:ios:72995daba29bb3e1dc83ee',
    messagingSenderId: '442635216043',
    projectId: 'pulse-45c54',
    storageBucket: 'pulse-45c54.firebasestorage.app',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsA-grYbenOCLuxz0uplBeSivelNKr_1M',
    appId: '1:442635216043:ios:72995daba29bb3e1dc83ee',
    messagingSenderId: '442635216043',
    projectId: 'pulse-45c54',
    storageBucket: 'pulse-45c54.firebasestorage.app',
    iosBundleId: 'com.example.pulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6FBWNCpJIaGh3w231l1faJDt9do6DyUU',
    appId: '1:442635216043:web:3cee864aeaf2c430dc83ee',
    messagingSenderId: '442635216043',
    projectId: 'pulse-45c54',
    authDomain: 'pulse-45c54.firebaseapp.com',
    storageBucket: 'pulse-45c54.firebasestorage.app',
    measurementId: 'G-XXNJ4RQ6EF',
  );
}
